name: Build macos_client

on:
  push:
    paths:
      - "macos_client/**"
      - "database/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/build-macos-client.yml"

permissions:
  contents: write

jobs:
  build:
    name: Build macos_client for multiple OS/ARCH
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build and zip for ${{ matrix.goos }}/${{ matrix.goarch }}
        run: |
          mkdir -p builds
          output_name="macos_client"
          binary_path="builds/${{ matrix.goos }}-${{ matrix.goarch }}/$output_name"

          mkdir -p "$(dirname "$binary_path")"

          # Build binary
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o "$binary_path" ./macos_client

          # Ensure it's executable
          chmod +x "$binary_path"

          # Zip the binary
          (cd "$(dirname "$binary_path")" && zip "${output_name}.zip" "$output_name")

      - name: Upload zipped artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}-zip
          path: builds/${{ matrix.goos }}-${{ matrix.goarch }}/macos_client.zip

  release:
    name: Create 'latest' GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all zipped artifacts
        uses: actions/download-artifact@v4
        with:
          path: builds

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Create or update 'latest' release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view latest &>/dev/null; then
            echo "Release 'latest' exists. Deleting and recreating..."
            gh release delete latest --yes
          fi

          gh release create latest \
            --title "Latest Build" \
            --notes "Automated build for latest commit" \
            --latest

      - name: Upload zip files to 'latest' release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find builds -type f -name "*.zip" -exec gh release upload latest {} --clobber \;
