name: Build macos_client

on:
  push:
    paths:
      - "macos_client/**"
      - "database/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/build-macos-client.yml"

permissions:
  contents: write # Required to create/update releases

jobs:
  build:
    name: Build macos_client for multiple OS/ARCH
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
        run: |
          mkdir -p builds
          ext=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            ext=".exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o builds/${{ matrix.goos }}-${{ matrix.goarch }}${ext} ./macos_client

      - name: Upload build artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}-build
          path: builds/${{ matrix.goos }}-${{ matrix.goarch }}*

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Create or update 'latest' release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view latest &>/dev/null; then
            echo "Release 'latest' exists. Deleting and recreating..."
            gh release delete latest --yes
          fi

          gh release create latest \
            --title "Latest Build" \
            --notes "Automated build for latest commit" \
            --latest

      - name: Upload binary to 'latest' release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload latest builds/${{ matrix.goos }}-${{ matrix.goarch }}* --clobber
